"""ContextStore protocol — CRUD for spec_contexts.json."""

from typing import Protocol

from dadaia_workspace.core.models.spec_context import SpecContextProject


class ContextStore(Protocol):
    def save(self, ctx: SpecContextProject) -> None: ...
    def update(self, ctx: SpecContextProject) -> None: ...
    def get(self, name: str) -> SpecContextProject | None: ...
    def list_all(self) -> list[SpecContextProject]: ...
    def delete(self, name: str) -> None: ...
