"""CourseStore protocol — CRUD for academy.json."""

from typing import Protocol

from dadaia_workspace.core.models.course import Course


class CourseStore(Protocol):
    def save(self, course: Course) -> None: ...
    def update(self, course: Course) -> None: ...
    def get(self, slug: str) -> Course | None: ...
    def list_all(self) -> list[Course]: ...
    def delete(self, slug: str) -> None: ...
