"""GitClient protocol — subprocess-based git operations."""

from pathlib import Path
from typing import Protocol


class GitClient(Protocol):
    def clone(self, url: str, dest: Path) -> None: ...
    def is_dirty(self, path: Path) -> bool: ...
    def commit_all(self, path: Path, msg: str) -> None: ...
    def has_remote(self, path: Path) -> bool: ...
    def push(self, path: Path) -> None: ...
