"""Git client protocol."""

from pathlib import Path
from typing import Protocol


class GitClient(Protocol):
    def clone(self, repo_ref: str, target_dir: Path) -> None: ...
    def is_git_repo(self, path: Path) -> bool: ...
    def has_changes(self, path: Path) -> bool: ...
    def has_remote(self, path: Path) -> bool: ...
    def commit_all(self, path: Path, message: str) -> None: ...
    def push(self, path: Path) -> None: ...
