"""GitClient protocol — subprocess-based git operations."""

from pathlib import Path
from typing import Protocol


class GitClient(Protocol):
    def clone(self, url: str, dest: Path) -> None: ...
    def is_dirty(self, path: Path) -> bool: ...
    def has_commits(self, path: Path) -> bool: ...
    def commit_all(self, path: Path, msg: str) -> None: ...
    def has_remote(self, path: Path) -> bool: ...
    def push(self, path: Path) -> None: ...
    def current_branch(self, path: Path) -> str: ...
    def checkout(self, path: Path, branch: str) -> None: ...
    def is_git_root(self, path: Path) -> bool: ...
    def list_untracked(self, path: Path) -> list[str]: ...
    def remote_url(self, path: Path) -> str: ...
    def upstream_branch(self, path: Path) -> str | None: ...
    def unpushed_commit_count(self, path: Path) -> int: ...
