"""Repository protocols for workspace and spec context persistence."""

from pathlib import Path
from typing import Protocol

from dadaia_workspace.core.models.spec_context import SpecContextProject
from dadaia_workspace.core.models.workspace import Workspace


class WorkspaceRepository(Protocol):
    def save(self, workspace: Workspace) -> None: ...
    def load(self, root: Path) -> Workspace | None: ...


class SpecContextRepository(Protocol):
    def save(self, ctx: SpecContextProject) -> None: ...
    def update(self, ctx: SpecContextProject) -> None: ...
    def get_by_name(self, name: str) -> SpecContextProject | None: ...
    def get_active(self) -> SpecContextProject | None: ...
    def list_all(self) -> list[SpecContextProject]: ...
    def delete(self, name: str) -> None: ...
