"""RunStateStore protocol — atomic persistence for orchestrate runs."""

from collections.abc import Iterable
from typing import Protocol

from dadaia_workspace.core.models.run_state import RunEvent, RunManifest


class RunStateStore(Protocol):
    def create_run(self, manifest: RunManifest) -> None: ...
    def load_run(self, run_id: str) -> RunManifest: ...
    def update_manifest(self, manifest: RunManifest) -> None: ...
    def append_event(self, event: RunEvent) -> None: ...
    def list_runs(self) -> tuple[RunManifest, ...]: ...
    def iter_events(self, run_id: str) -> Iterable[RunEvent]: ...
