"""ServerRegistryStore Protocol — port registry CRUD."""

from typing import Protocol

from dadaia_workspace.core.models.server_registry import PortEntry


class ServerRegistryStore(Protocol):
    def save(self, entry: PortEntry) -> None: ...
    def update(self, entry: PortEntry) -> None: ...
    def get(self, port: int) -> PortEntry | None: ...
    def list_all(self) -> list[PortEntry]: ...
    def delete(self, port: int) -> None: ...
