"""Unit tests for dadaia_workspace.features.spec_artifacts.memory.

Covers:
- T-MMS-04: born-markdown scaffold — .md files with valid frontmatter; lint passes
- AC-T3-2 (updated T-MMS-04): memory_product_add creates feature .md
- AC-T3-3: idempotent re-run produces same slug_entries
- AC-C-6 (updated T-MMS-04): dadaia memory product add <slug> creates .md
- AC-C-7: idempotent on repeated calls

REMOVED (memory-markdown-source-v1 T-MMS-10/11):
- TestScaffoldIndexHtml — validated legacy YAML scaffold stubs and rendered index.html;
  the YAML stubs (index.yaml, architecture.yaml, tech-stack.yaml), the Jinja templates,
  and placeholder.html were all deleted.  index.html is no longer generated by
  memory_product_add.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

import pytest

from dadaia_workspace.features.spec_artifacts.memory import (
    MemoryProductAddResult,
    memory_product_add,
)

_SCAFFOLD_DIR = (
    Path(__file__).parent.parent.parent.parent.parent / "dadaia_workspace" / "public" / "scaffold"
)


# ── memory_product_add unit tests (AC-T3-2, AC-T3-3, T-MMS-04) ───────────────

# Path to lint-memory-atoms.py script (used in T-MMS-04 gate assertions).
_LINT_SCRIPT = (
    Path(__file__).parent.parent.parent.parent.parent
    / "dadaia_workspace"
    / "public"
    / "scripts"
    / "lint-memory-atoms.py"
)


class TestMemoryProductAdd:
    """Tests for memory_product_add feature function.

    Updated in T-MMS-04 / T-MMS-10/11: the function writes <slug>.md (born-markdown).
    index.html is no longer generated (the template was retired with the YAML pipeline).
    """

    def test_creates_feature_md(self, tmp_path: Path) -> None:
        """T-MMS-04 / AC-C-6 (updated): creates specs/memory/product/<slug>.md."""
        specs = tmp_path / "specs"
        specs.mkdir()

        result = memory_product_add(specs, "payments")

        assert isinstance(result, MemoryProductAddResult)
        feature = specs / "memory" / "product" / "payments.md"
        assert feature.is_file(), "payments.md must be created (T-MMS-04)"
        assert result.created_feature is True
        assert result.feature_html == feature

    def test_feature_md_has_valid_frontmatter(self, tmp_path: Path) -> None:
        """T-MMS-04: the created .md file has YAML frontmatter with required fields."""
        specs = tmp_path / "specs"
        specs.mkdir()

        memory_product_add(specs, "payments")

        content = (specs / "memory" / "product" / "payments.md").read_text(encoding="utf-8")
        # Must start with frontmatter delimiter
        assert content.startswith("---\n"), "Markdown atom must start with --- frontmatter"

        import yaml as _yaml

        fm_match = re.match(r"^---\s*\n(.*?)\n---\s*\n", content, re.DOTALL)
        assert fm_match, "No valid YAML frontmatter block found"
        fm = _yaml.safe_load(fm_match.group(1))

        required = {
            "slug",
            "title",
            "category",
            "tldr",
            "summary",
            "tags",
            "agent_tier",
            "token_estimate",
            "last_updated",
            "release_origin",
        }
        missing = required - set(fm.keys())
        assert not missing, f"Frontmatter missing required fields: {missing}"

    def test_feature_md_slug_matches_filename(self, tmp_path: Path) -> None:
        """T-MMS-04: frontmatter slug must equal the file stem (payments)."""
        import yaml as _yaml

        specs = tmp_path / "specs"
        specs.mkdir()

        memory_product_add(specs, "payments")

        content = (specs / "memory" / "product" / "payments.md").read_text(encoding="utf-8")
        fm_match = re.match(r"^---\s*\n(.*?)\n---\s*\n", content, re.DOTALL)
        assert fm_match
        fm = _yaml.safe_load(fm_match.group(1))
        assert fm["slug"] == "payments", f"Expected slug='payments', got {fm['slug']!r}"

    def test_feature_md_passes_lint(self, tmp_path: Path) -> None:
        """T-MMS-04 gate: the scaffolded .md passes lint-memory-atoms.py (exit 0 or 2 warn-only)."""
        specs = tmp_path / "specs"
        specs.mkdir()

        memory_product_add(specs, "my-feature")

        memory_dir = specs / "memory"
        proc = subprocess.run(
            [sys.executable, str(_LINT_SCRIPT), "--memory-dir", str(memory_dir)],
            capture_output=True,
            text=True,
        )
        # Exit 0 = clean, exit 2 = warnings only. Exit 1 = ERROR (must not happen).
        assert proc.returncode != 1, (
            f"lint-memory-atoms.py returned ERROR (exit 1) for scaffolded atom.\n"
            f"stdout:\n{proc.stdout}\nstderr:\n{proc.stderr}"
        )

    def test_idempotent_call_does_not_recreate_feature(self, tmp_path: Path) -> None:
        """AC-T3-3 / AC-C-7: calling add twice with the same slug does not re-create the file."""
        specs = tmp_path / "specs"
        specs.mkdir()

        # First call
        result1 = memory_product_add(specs, "payments")
        assert result1.created_feature is True

        # Second call with same slug
        result2 = memory_product_add(specs, "payments")
        assert result2.created_feature is False, (
            "Second call must not re-create the existing feature Markdown atom"
        )
        # Both must report payments in slug_entries
        assert "payments" in result1.slug_entries
        assert "payments" in result2.slug_entries

    def test_slug_entries_sorted(self, tmp_path: Path) -> None:
        """slug_entries must be in lexicographic order after multiple adds."""
        specs = tmp_path / "specs"
        specs.mkdir()

        memory_product_add(specs, "zebra")
        memory_product_add(specs, "alpha")
        result = memory_product_add(specs, "middle")

        assert result.slug_entries == sorted(result.slug_entries), (
            "slug_entries must be in lexicographic order"
        )
        assert result.slug_entries == ["alpha", "middle", "zebra"]

    def test_invalid_slug_raises_value_error(self, tmp_path: Path) -> None:
        """Invalid slug must raise ValueError."""
        specs = tmp_path / "specs"
        specs.mkdir()

        with pytest.raises(ValueError, match=r"Invalid slug"):
            memory_product_add(specs, "INVALID SLUG")

    def test_slug_starting_with_digit_raises(self, tmp_path: Path) -> None:
        """Slug starting with a digit is invalid."""
        specs = tmp_path / "specs"
        specs.mkdir()

        with pytest.raises(ValueError, match=r"Invalid slug"):
            memory_product_add(specs, "1bad")

    def test_product_dir_created_if_absent(self, tmp_path: Path) -> None:
        """specs/memory/product/ is created automatically if missing."""
        specs = tmp_path / "specs"
        specs.mkdir()

        assert not (specs / "memory" / "product").exists()
        memory_product_add(specs, "auth")
        assert (specs / "memory" / "product").is_dir()


# ── T-MMS-04: born-markdown scaffold file assertions ─────────────────────────


class TestBornMarkdownScaffolds:
    """T-MMS-04: verify .md scaffold files exist and pass lint."""

    def test_architecture_md_scaffold_exists(self) -> None:
        """T-MMS-04: public/scaffold/memory/architecture.md must exist."""
        path = _SCAFFOLD_DIR / "memory" / "architecture.md"
        assert path.is_file(), f"architecture.md scaffold missing at {path}"

    def test_tech_stack_md_scaffold_exists(self) -> None:
        """T-MMS-04: public/scaffold/memory/tech-stack.md must exist."""
        path = _SCAFFOLD_DIR / "memory" / "tech-stack.md"
        assert path.is_file(), f"tech-stack.md scaffold missing at {path}"

    def test_product_index_md_scaffold_exists(self) -> None:
        """T-MMS-04: public/scaffold/memory/product/index.md must exist."""
        path = _SCAFFOLD_DIR / "memory" / "product" / "index.md"
        assert path.is_file(), f"product/index.md scaffold missing at {path}"

    def test_feature_md_scaffold_exists(self) -> None:
        """T-MMS-04: public/scaffold/memory/product/feature.md must exist."""
        path = _SCAFFOLD_DIR / "memory" / "product" / "feature.md"
        assert path.is_file(), f"product/feature.md scaffold missing at {path}"

    def test_architecture_md_has_frontmatter(self) -> None:
        """T-MMS-04: architecture.md scaffold has valid YAML frontmatter."""
        import yaml as _yaml

        path = _SCAFFOLD_DIR / "memory" / "architecture.md"
        content = path.read_text(encoding="utf-8")
        assert content.startswith("---\n")
        fm_match = re.match(r"^---\s*\n(.*?)\n---\s*\n", content, re.DOTALL)
        assert fm_match, "No frontmatter block found in architecture.md scaffold"
        fm = _yaml.safe_load(fm_match.group(1))
        assert fm.get("slug") == "architecture"
        assert fm.get("category") == "core"

    def test_tech_stack_md_has_frontmatter(self) -> None:
        """T-MMS-04: tech-stack.md scaffold has valid YAML frontmatter."""
        import yaml as _yaml

        path = _SCAFFOLD_DIR / "memory" / "tech-stack.md"
        content = path.read_text(encoding="utf-8")
        assert content.startswith("---\n")
        fm_match = re.match(r"^---\s*\n(.*?)\n---\s*\n", content, re.DOTALL)
        assert fm_match
        fm = _yaml.safe_load(fm_match.group(1))
        assert fm.get("slug") == "tech-stack"
        assert fm.get("category") == "core"

    def test_product_index_md_has_frontmatter(self) -> None:
        """T-MMS-04: product/index.md scaffold has valid YAML frontmatter."""
        import yaml as _yaml

        path = _SCAFFOLD_DIR / "memory" / "product" / "index.md"
        content = path.read_text(encoding="utf-8")
        assert content.startswith("---\n")
        fm_match = re.match(r"^---\s*\n(.*?)\n---\s*\n", content, re.DOTALL)
        assert fm_match
        fm = _yaml.safe_load(fm_match.group(1))
        assert fm.get("slug") == "index"
        assert fm.get("category") == "product"

    def test_architecture_md_passes_lint(self, tmp_path: Path) -> None:
        """T-MMS-04 gate: architecture.md scaffold passes lint-memory-atoms.py."""
        import shutil

        # Copy scaffold to a temp memory dir so the linter can find it.
        mem_dir = tmp_path / "memory"
        mem_dir.mkdir()
        shutil.copy(_SCAFFOLD_DIR / "memory" / "architecture.md", mem_dir / "architecture.md")

        proc = subprocess.run(
            [sys.executable, str(_LINT_SCRIPT), "--memory-dir", str(mem_dir)],
            capture_output=True,
            text=True,
        )
        assert proc.returncode != 1, (
            f"architecture.md scaffold failed lint (exit 1).\n"
            f"stdout:\n{proc.stdout}\nstderr:\n{proc.stderr}"
        )

    def test_tech_stack_md_passes_lint(self, tmp_path: Path) -> None:
        """T-MMS-04 gate: tech-stack.md scaffold passes lint-memory-atoms.py."""
        import shutil

        mem_dir = tmp_path / "memory"
        mem_dir.mkdir()
        shutil.copy(_SCAFFOLD_DIR / "memory" / "tech-stack.md", mem_dir / "tech-stack.md")

        proc = subprocess.run(
            [sys.executable, str(_LINT_SCRIPT), "--memory-dir", str(mem_dir)],
            capture_output=True,
            text=True,
        )
        assert proc.returncode != 1, (
            f"tech-stack.md scaffold failed lint (exit 1).\n"
            f"stdout:\n{proc.stdout}\nstderr:\n{proc.stderr}"
        )

    def test_product_index_md_passes_lint(self, tmp_path: Path) -> None:
        """T-MMS-04 gate: product/index.md scaffold passes lint-memory-atoms.py."""
        import shutil

        mem_dir = tmp_path / "memory"
        product_dir = mem_dir / "product"
        product_dir.mkdir(parents=True)
        shutil.copy(
            _SCAFFOLD_DIR / "memory" / "product" / "index.md",
            product_dir / "index.md",
        )

        proc = subprocess.run(
            [sys.executable, str(_LINT_SCRIPT), "--memory-dir", str(mem_dir)],
            capture_output=True,
            text=True,
        )
        assert proc.returncode != 1, (
            f"product/index.md scaffold failed lint (exit 1).\n"
            f"stdout:\n{proc.stdout}\nstderr:\n{proc.stderr}"
        )
