"""AC-O-1: Onboarding E2E — copytree-from-scaffold path → v2 tree → doctor exit-0.

Exercises the exact onboarding path that `dadaia context activate` uses:
  shutil.copytree(_SCAFFOLD_SRC, specs_dir)
from dadaia_workspace/public/scaffold/ into a fresh tmp_path/specs.

This is distinct from AC-T9-15 (which exercises the scaffold() function path).

T-MSS-06 note: The scaffold now ships YAML stubs (not HTML files) for the 3
structural memory atoms.  HTML is rendered from YAML via `dadaia memory render`
or the `scaffold()` function.  The copytree path therefore:
  - DOES contain YAML stubs (architecture.yaml, tech-stack.yaml, product/index.yaml).
  - Does NOT contain HTML files for those atoms (TREE-3 WARNs are expected).
  - TREE-3 WARNs are warnings, not errors; they guide the operator to run render.
  - placeholder.html exists to satisfy the index.yaml catalog link check.
"""

from __future__ import annotations

import shutil
from pathlib import Path

import yaml

from dadaia_workspace.features.specs import Severity, SpecsDoctor
from dadaia_workspace.features.specs.renderer import validate_atom

# Repo root: tests/integration/test_onboarding_tree_v2_e2e.py → 3 parents up = repo root
_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
_SCAFFOLD_SRC = _REPO_ROOT / "dadaia_workspace" / "public" / "scaffold"
_PUBLIC_DIR = _REPO_ROOT / "dadaia_workspace" / "public"
_TEMPLATES_DIR = _PUBLIC_DIR / "templates"


def test_ac_o1_copytree_scaffold_produces_valid_v2_tree(tmp_path: Path) -> None:
    """AC-O-1 (updated T-MSS-06): A specs/ tree materialised via copytree from public/scaffold/
    (the exact mechanism used by `dadaia context activate`) must:
      1. Contain the v2 mandatory directories (backlog/, bugs/, releases/) each with
         README.md and .gitkeep.
      2. Contain the memory YAML stubs (architecture.yaml, tech-stack.yaml,
         product/index.yaml), each valid against their schema (AC-C5-1..3).
         NOTE: HTML files are NOT present after copytree — they are generated by
         `dadaia memory render` or the scaffold() function (T-MSS-06 design).
      3. Contain specs/AGENTS.md (the SDD workflow contract).
      4. NOT contain specs/foundation/ or specs/SPEC.md at the tree root.
      5. Produce 0 TREE-* ERROR-severity issues when SpecsDoctor.check() is run.
         TREE-3 WARNs (HTML absent) are expected and acceptable for copytree path;
         they are resolved by running `dadaia memory render` after onboarding.
    """
    specs_dir = tmp_path / "specs"

    # --- Onboarding: copy scaffold exactly as context activate does ---
    shutil.copytree(_SCAFFOLD_SRC, specs_dir)

    # ---- Assertion 1: v2 mandatory directories ----
    for dirname in ("backlog", "bugs", "releases"):
        d = specs_dir / dirname
        assert d.exists(), f"specs/{dirname}/ must exist after copytree-from-scaffold"
        assert d.is_dir(), f"specs/{dirname} must be a directory"
        assert (d / "README.md").exists(), f"specs/{dirname}/README.md must exist"
        assert (d / ".gitkeep").exists(), f"specs/{dirname}/.gitkeep must exist"

    # ---- Assertion 2 (T-MSS-06): memory YAML stubs exist and validate ----
    # After T-MSS-06, the scaffold ships YAML stubs (not HTML). HTML is generated
    # by `dadaia memory render` — it is NOT present after a bare copytree.
    yaml_stubs = [
        (specs_dir / "memory" / "architecture.yaml", "memory-architecture-v1"),
        (specs_dir / "memory" / "tech-stack.yaml", "memory-tech-stack-v1"),
        (specs_dir / "memory" / "product" / "index.yaml", "memory-product-index-v1"),
    ]
    for yaml_path, atom_type in yaml_stubs:
        assert yaml_path.exists(), f"{yaml_path.relative_to(tmp_path)} must exist (AC-C5-1..3)"
        data = yaml.safe_load(yaml_path.read_text(encoding="utf-8"))
        assert isinstance(data, dict), f"{yaml_path.name} must be a YAML mapping"
        # Validate against schema (AC-C5-1..3) — must not raise.
        validate_atom(data, atom_type)

    # placeholder.html must exist (satisfies the index.yaml catalog link).
    placeholder_html = specs_dir / "memory" / "product" / "placeholder.html"
    assert placeholder_html.exists(), (
        "specs/memory/product/placeholder.html must exist after copytree-from-scaffold "
        "(satisfies the placeholder catalog entry in index.yaml)"
    )

    # ---- Assertion 3: specs/AGENTS.md exists (SDD workflow contract) ----
    agents_md = specs_dir / "AGENTS.md"
    assert agents_md.exists(), "specs/AGENTS.md must exist after copytree-from-scaffold"

    # ---- Assertion 4: deprecated v1 artifacts must NOT be present ----
    assert not (specs_dir / "foundation").exists(), (
        "specs/foundation/ must NOT exist in a v2 scaffold tree"
    )
    assert not (specs_dir / "SPEC.md").exists(), (
        "specs/SPEC.md at the tree root must NOT exist in a v2 scaffold tree"
    )

    # ---- Assertion 5 (AC-O-1 core, updated T-MSS-06): SpecsDoctor reports 0 TREE-* ERRORs ----
    # A fresh scaffold has no ACTIVE.md yet (that is populated when the first release
    # is created, not during onboarding), so SPEC-DOC-003 is expected and acceptable.
    # T-MSS-06: TREE-3 WARNs (HTML absent for YAML-source atoms) are now expected on
    # the copytree path since HTML is generated on demand, not shipped in scaffold.
    # The critical invariant is 0 TREE-* ERROR-severity issues.
    doctor = SpecsDoctor(specs_dir, public_dir=_PUBLIC_DIR)
    issues = doctor.check()

    # Zero TREE-* ERROR-severity issues.
    tree_errors = [i for i in issues if i.code.startswith("TREE-") and i.severity == Severity.ERROR]
    assert tree_errors == [], (
        "Fresh copytree-from-scaffold specs/ must produce 0 TREE-* ERROR issues:\n"
        + "\n".join(f"  {i.code}: {i.description}" for i in tree_errors)
    )
