"""dadaia import command."""

from pathlib import Path
from typing import Annotated, Optional

import typer
from rich.console import Console

from dadaia_workspace.core.models.import_ import ImportOptions
from dadaia_workspace.features.import_.service import ImportService

console = Console()
err_console = Console(stderr=True)


def import_workspace(
    archive: Annotated[
        Path,
        typer.Argument(help="Path to the .tar.gz archive generated by 'dadaia export'."),
    ],
    workspace: Annotated[
        Optional[Path],
        typer.Option("--workspace", "-w", help="Destination workspace root (default: cwd)."),
    ] = None,
    skip_mnt: Annotated[
        bool,
        typer.Option("--skip-mnt", help="Do not extract mnt/ container volumes."),
    ] = False,
    skip_activate: Annotated[
        bool,
        typer.Option(
            "--skip-activate",
            help="Skip context activation; leave all contexts as inativo.",
        ),
    ] = False,
    dry_run: Annotated[
        bool,
        typer.Option("--dry-run", help="Preview what would happen without changing anything."),
    ] = False,
) -> None:
    """Import a workspace from a dadaia export archive.

    Extracts the archive, patches absolute paths for the new workspace root,
    runs 'dadaia init', and re-activates all contexts that were active at
    export time.

    Typical usage on a new machine after cloning dadaia-workspace and running
    'pip install -e .':

    \b
        cd ~/workspace
        dadaia import /path/to/workspace-2026-05-12-100000.tar.gz
        dadaia import /path/to/workspace-2026-05-12-100000.tar.gz --skip-mnt
    """
    resolved_workspace = (workspace or Path.cwd()).resolve()
    options = ImportOptions(
        archive=archive.resolve(),
        workspace=resolved_workspace,
        skip_mnt=skip_mnt,
        skip_activate=skip_activate,
        dry_run=dry_run,
    )

    try:
        svc = ImportService(workspace_root=resolved_workspace)
        result = svc.run(options)
    except ValueError as exc:
        err_console.print(f"[red]Error:[/red] {exc}")
        raise typer.Exit(1) from None

    if dry_run:
        return

    console.print(
        f"\n[green]✓[/green] Workspace imported at [bold]{result.workspace_root}[/bold]"
    )
    console.print(f"  Source: {options.archive.name}")

    if result.contexts_restored:
        console.print(f"\nContexts restored ({len(result.contexts_restored)}):")
        for name in result.contexts_restored:
            console.print(f"  [green]✓[/green] {name}")

    if result.errors:
        console.print("\n[yellow]Activation errors (check network/git access):[/yellow]")
        for err in result.errors:
            console.print(f"  [red]✗[/red] {err}")

    console.print("\n[dim]Next steps:[/dim]")
    console.print("  [dim]• Add secrets to services/conf/*.env (not included in export)[/dim]")
    console.print("  [dim]• Run 'dadaia doctor' to verify workspace consistency[/dim]")
