"""Intent: CONTRACT — DADAIA §8.3 public asset hygiene (no bytecode under public/, build excludes)

Public-source hygiene contract (FR-W5-01 / AC-W5-01, release v0.1.11).

Residual R7: ``dadaia_workspace/public/scripts/__pycache__/`` had been committed —
compiled bytecode leaking into the canonical public asset tree, which is source-of-truth
for every consumer and is staged/projected verbatim. Two failure modes must stay closed:

1. **Regeneration.** Running the public scripts (``lint-memory-atoms.py`` —
   ``generate-memory-catalog.py`` DELETED, v0.5.1 T-051-16/A10.1/A10.4) must NOT drop a
   ``__pycache__/*.pyc`` under ``dadaia_workspace/public/``. The script sets
   ``sys.dont_write_bytecode = True`` so the guard fires for any invocation style;
   ``features/specs/doctor_memory.py`` additionally passes ``-B`` at the LINT-1 subprocess
   call site. This test executes the script WITHOUT ``-B`` so it proves the in-script guard,
   not just the call-site flag.

2. **Packaging.** The built wheel/sdist must contain no ``.pyc``. ``poetry-core`` honours
   the ``[tool.poetry] exclude`` globs for both artifacts; this test asserts the exclusion
   config is present (cheap — no full build invocation, which would be network/poetry
   dependent and is the final-gate's job).
"""

from __future__ import annotations

import subprocess
import sys
import tomllib
from pathlib import Path

import pytest

from tests.helpers.scan_population import assert_populated

pytestmark = pytest.mark.contract

_REPO_ROOT = Path(__file__).resolve().parents[2]
_PUBLIC_ROOT = _REPO_ROOT / "dadaia_workspace" / "public"
_SCRIPTS_DIR = _PUBLIC_ROOT / "scripts"
_MEMORY_DIR = _REPO_ROOT / "specs" / "memory"


def _bytecode_artifacts_under_public() -> list[str]:
    """Every committed/regenerated bytecode artifact under public/ (relative paths)."""
    pyc = [str(p.relative_to(_REPO_ROOT)) for p in _PUBLIC_ROOT.rglob("*.pyc")]
    caches = [str(p.relative_to(_REPO_ROOT)) for p in _PUBLIC_ROOT.rglob("__pycache__")]
    return sorted(pyc + caches)


def test_pre_push_ci_gate_ships_pyproject_excludes_bytecode_and_scripts_leave_no_pycache() -> None:
    """`pre-push-ci-gate.sh` is present in the public/scripts/ listing (the SINGLE
    explicit ship assertion for the pre-push gate script, suite-wide, v0.1.51 FR3),
    and the poetry-core build config excludes __pycache__/*.pyc from sdist and wheel.

    Also: the canonical public asset tree carries no bytecode at rest (precondition),
    and executing the catalog + lint scripts must not write __pycache__ under public/.
    Invoked WITHOUT ``-B`` so the in-script ``sys.dont_write_bytecode`` guard is what is
    under test (the call-site ``-B`` would mask a missing guard).
    """
    listing = {p.name for p in _SCRIPTS_DIR.iterdir()}
    # v0.4.5 FR5 (scan-test-vacuity-guard): the two membership asserts already imply
    # non-emptiness; expressed via the shared convention for grep-ability.
    assert_populated(listing, sentinel="pre-push-ci-gate.sh")
    assert "certify-dadaia-workspace.sh" in listing

    pyproject = _REPO_ROOT / "pyproject.toml"
    data = tomllib.loads(pyproject.read_text(encoding="utf-8"))
    exclude = data["tool"]["poetry"].get("exclude", [])
    assert "**/__pycache__" in exclude
    assert "**/*.pyc" in exclude

    if not _MEMORY_DIR.is_dir():
        pytest.skip("specs/memory not present in this checkout")

    before = _bytecode_artifacts_under_public()
    assert before == [], f"precondition: public/ already polluted: {before}"

    lint_script = _SCRIPTS_DIR / "lint-memory-atoms.py"
    assert lint_script.is_file()

    # lint exits 0 (clean) or 2 (warnings only); either is a valid run that imports the
    # script module and would otherwise drop a .pyc.
    lint = subprocess.run(
        [sys.executable, str(lint_script), "--memory-dir", str(_MEMORY_DIR)],
        cwd=_REPO_ROOT,
        capture_output=True,
        check=False,
    )
    assert lint.returncode in (0, 2), lint.stderr.decode()

    after = _bytecode_artifacts_under_public()
    assert after == [], f"script left bytecode under public/: {after}"


_RETIRED_SURFACES: tuple[str, ...] = (
    ".dadaia/reports",
    "academy",
    "dadaia clean",
    "tmp gc",
    "reports cleanup",
    "ROOT-4",
    "legacy-quarantine",
)


def test_public_source_names_no_retired_surface() -> None:
    """Intent: CONTRACT — 0.4.6 c4 AC13 (FR16, D2/D3/D9): no `public/` text names a retired surface.

    The reports zone, academy, `dadaia clean`, `dadaia tmp gc`, `dadaia reports cleanup`,
    the `ROOT-4` invariant and the legacy quarantine were retired; the law, skills,
    personas, templates and entities that are staged verbatim to every consumer must not
    keep teaching them. Mirrors the SPEC's own grep exactly, so the verdict is the same
    one the operator runs by hand.
    """
    hits: list[str] = []
    scanned: list[str] = []
    for path in sorted(_PUBLIC_ROOT.rglob("*")):
        if not path.is_file():
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        rel = path.relative_to(_REPO_ROOT).as_posix()
        scanned.append(rel)
        for lineno, line in enumerate(text.splitlines(), start=1):
            for needle in _RETIRED_SURFACES:
                if needle in line:
                    hits.append(f"{rel}:{lineno}: {needle!r}")
    assert_populated(scanned, "dadaia_workspace/public/data/DADAIA.md")
    assert hits == []
