"""Public-source hygiene contract (FR-W5-01 / AC-W5-01, release v0.1.11).

Residual R7: ``dadaia_workspace/public/scripts/__pycache__/`` had been committed —
compiled bytecode leaking into the canonical public asset tree, which is source-of-truth
for every consumer and is staged/projected verbatim. Two failure modes must stay closed:

1. **Regeneration.** Running the public scripts (``lint-memory-atoms.py`` /
   ``generate-memory-catalog.py``) must NOT drop a ``__pycache__/*.pyc`` under
   ``dadaia_workspace/public/``. The scripts set ``sys.dont_write_bytecode = True`` so the
   guard fires for any invocation style; ``features/specs/doctor.py`` additionally passes
   ``-B`` at the LINT-1 subprocess call site. This test executes the scripts WITHOUT
   ``-B`` so it proves the in-script guard, not just the call-site flag.

2. **Packaging.** The built wheel/sdist must contain no ``.pyc``. ``poetry-core`` honours
   the ``[tool.poetry] exclude`` globs for both artifacts; this test asserts the exclusion
   config is present (cheap — no full build invocation, which would be network/poetry
   dependent and is the final-gate's job).
"""

from __future__ import annotations

import subprocess
import sys
import tomllib
from pathlib import Path

import pytest

pytestmark = pytest.mark.contract

_REPO_ROOT = Path(__file__).resolve().parents[2]
_PUBLIC_ROOT = _REPO_ROOT / "dadaia_workspace" / "public"
_SCRIPTS_DIR = _PUBLIC_ROOT / "scripts"
_MEMORY_DIR = _REPO_ROOT / "specs" / "memory"


def _bytecode_artifacts_under_public() -> list[str]:
    """Every committed/regenerated bytecode artifact under public/ (relative paths)."""
    pyc = [str(p.relative_to(_REPO_ROOT)) for p in _PUBLIC_ROOT.rglob("*.pyc")]
    caches = [str(p.relative_to(_REPO_ROOT)) for p in _PUBLIC_ROOT.rglob("__pycache__")]
    return sorted(pyc + caches)


def test_no_bytecode_committed_under_public() -> None:
    """The canonical public asset tree carries no bytecode at rest."""
    assert _bytecode_artifacts_under_public() == []


def test_pre_push_ci_gate_script_ships() -> None:
    """`pre-push-ci-gate.sh` is present in the public/scripts/ listing.

    The SINGLE explicit ship assertion for the pre-push gate script, suite-wide
    (v0.1.51 FR3): tests that *execute* the script (e.g. the venv-probe suite) are
    behavior tests, not ship assertions, and must not duplicate this presence check.
    Relocated here from the retired ``test_bash_hook_residue.py``.
    """
    listing = {p.name for p in _SCRIPTS_DIR.iterdir()}
    assert "pre-push-ci-gate.sh" in listing


def test_running_public_scripts_leaves_no_pycache(tmp_path: Path) -> None:
    """Executing the catalog + lint scripts must not write __pycache__ under public/.

    Invoked WITHOUT ``-B`` so the in-script ``sys.dont_write_bytecode`` guard is what is
    under test (the call-site ``-B`` would mask a missing guard).
    """
    if not _MEMORY_DIR.is_dir():
        pytest.skip("specs/memory not present in this checkout")

    before = _bytecode_artifacts_under_public()
    assert before == [], f"precondition: public/ already polluted: {before}"

    lint_script = _SCRIPTS_DIR / "lint-memory-atoms.py"
    gen_script = _SCRIPTS_DIR / "generate-memory-catalog.py"
    assert lint_script.is_file()
    assert gen_script.is_file()

    # lint exits 0 (clean) or 2 (warnings only); either is a valid run that imports the
    # script module and would otherwise drop a .pyc.
    lint = subprocess.run(
        [sys.executable, str(lint_script), "--memory-dir", str(_MEMORY_DIR)],
        cwd=_REPO_ROOT,
        capture_output=True,
        check=False,
    )
    assert lint.returncode in (0, 2), lint.stderr.decode()

    out_catalog = tmp_path / "catalog.json"
    gen = subprocess.run(
        [
            sys.executable,
            str(gen_script),
            "--memory-dir",
            str(_MEMORY_DIR),
            "--out",
            str(out_catalog),
        ],
        cwd=_REPO_ROOT,
        capture_output=True,
        check=False,
    )
    assert gen.returncode == 0, gen.stderr.decode()

    after = _bytecode_artifacts_under_public()
    assert after == [], f"scripts left bytecode under public/: {after}"


def test_pyproject_excludes_bytecode_from_build() -> None:
    """poetry-core build must exclude __pycache__/*.pyc from sdist and wheel."""
    pyproject = _REPO_ROOT / "pyproject.toml"
    data = tomllib.loads(pyproject.read_text(encoding="utf-8"))
    exclude = data["tool"]["poetry"].get("exclude", [])
    assert "**/__pycache__" in exclude
    assert "**/*.pyc" in exclude
