"""Intent: CONTRACT — DADAIA §8.3 public asset hygiene (no bytecode under public/, build excludes)

Public-source hygiene contract (FR-W5-01 / AC-W5-01, release v0.1.11).

Residual R7: ``dadaia_workspace/public/scripts/__pycache__/`` had been committed —
compiled bytecode leaking into the canonical public asset tree, which is source-of-truth
for every consumer and is staged/projected verbatim. Two failure modes must stay closed:

1. **Regeneration.** Running the public scripts (``lint-memory-atoms.py`` —
   ``generate-memory-catalog.py`` DELETED, v0.5.1 T-051-16/A10.1/A10.4) must NOT drop a
   ``__pycache__/*.pyc`` under ``dadaia_workspace/public/``. The script sets
   ``sys.dont_write_bytecode = True`` so the guard fires for any invocation style;
   ``features/specs/doctor_memory.py`` additionally passes ``-B`` at the LINT-1 subprocess
   call site. This test executes the script WITHOUT ``-B`` so it proves the in-script guard,
   not just the call-site flag.

2. **Packaging.** The built wheel/sdist must contain no ``.pyc``. ``poetry-core`` honours
   the ``[tool.poetry] exclude`` globs for both artifacts; this test asserts the exclusion
   config is present (cheap — no full build invocation, which would be network/poetry
   dependent and is the final-gate's job).
"""

from __future__ import annotations

import re
import subprocess
import sys
import tomllib
from pathlib import Path

import pytest

from dadaia_workspace.infrastructure.privacy_check import PORTUGUESE_CONTROL_TERMS
from tests.helpers.scan_population import assert_populated

pytestmark = pytest.mark.contract

_REPO_ROOT = Path(__file__).resolve().parents[2]
_PUBLIC_ROOT = _REPO_ROOT / "dadaia_workspace" / "public"
_SCRIPTS_DIR = _PUBLIC_ROOT / "scripts"
_MEMORY_DIR = _REPO_ROOT / "specs" / "memory"


def _bytecode_artifacts_under_public() -> list[str]:
    """Every committed/regenerated bytecode artifact under public/ (relative paths)."""
    pyc = [str(p.relative_to(_REPO_ROOT)) for p in _PUBLIC_ROOT.rglob("*.pyc")]
    caches = [str(p.relative_to(_REPO_ROOT)) for p in _PUBLIC_ROOT.rglob("__pycache__")]
    return sorted(pyc + caches)


def test_pre_push_ci_gate_ships_pyproject_excludes_bytecode_and_scripts_leave_no_pycache() -> None:
    """`pre-push-ci-gate.sh` is present in the public/scripts/ listing (the SINGLE
    explicit ship assertion for the pre-push gate script, suite-wide, v0.1.51 FR3),
    and the poetry-core build config excludes __pycache__/*.pyc from sdist and wheel.

    Also: the canonical public asset tree carries no bytecode at rest (precondition),
    and executing the catalog + lint scripts must not write __pycache__ under public/.
    Invoked WITHOUT ``-B`` so the in-script ``sys.dont_write_bytecode`` guard is what is
    under test (the call-site ``-B`` would mask a missing guard).
    """
    listing = {p.name for p in _SCRIPTS_DIR.iterdir()}
    # v0.4.5 FR5 (scan-test-vacuity-guard): the two membership asserts already imply
    # non-emptiness; expressed via the shared convention for grep-ability.
    assert_populated(listing, sentinel="pre-push-ci-gate.sh")
    assert "certify-dadaia-workspace.sh" in listing

    pyproject = _REPO_ROOT / "pyproject.toml"
    data = tomllib.loads(pyproject.read_text(encoding="utf-8"))
    exclude = data["tool"]["poetry"].get("exclude", [])
    assert "**/__pycache__" in exclude
    assert "**/*.pyc" in exclude

    if not _MEMORY_DIR.is_dir():
        pytest.skip("specs/memory not present in this checkout")

    before = _bytecode_artifacts_under_public()
    assert before == [], f"precondition: public/ already polluted: {before}"

    lint_script = _SCRIPTS_DIR / "lint-memory-atoms.py"
    assert lint_script.is_file()

    # lint exits 0 (clean) or 2 (warnings only); either is a valid run that imports the
    # script module and would otherwise drop a .pyc.
    lint = subprocess.run(
        [sys.executable, str(lint_script), "--memory-dir", str(_MEMORY_DIR)],
        cwd=_REPO_ROOT,
        capture_output=True,
        check=False,
    )
    assert lint.returncode in (0, 2), lint.stderr.decode()

    after = _bytecode_artifacts_under_public()
    assert after == [], f"script left bytecode under public/: {after}"


_RETIRED_SURFACES: tuple[str, ...] = (
    ".dadaia/reports",
    "academy",
    "dadaia clean",
    "tmp gc",
    "reports cleanup",
    "ROOT-4",
    "legacy-quarantine",
    "repos catalog",
)


def test_public_source_names_no_retired_surface() -> None:
    """Intent: CONTRACT — 0.4.6 c4 AC13 (FR16, D2/D3/D9): no `public/` text names a retired surface.

    The reports zone, academy, `dadaia clean`, `dadaia tmp gc`, `dadaia reports cleanup`,
    the `ROOT-4` invariant and the legacy quarantine were retired; the law, skills,
    personas, templates and entities that are staged verbatim to every consumer must not
    keep teaching them. Mirrors the SPEC's own grep exactly, so the verdict is the same
    one the operator runs by hand.
    """
    hits: list[str] = []
    scanned: list[str] = []
    for path in sorted(_PUBLIC_ROOT.rglob("*")):
        if not path.is_file():
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        rel = path.relative_to(_REPO_ROOT).as_posix()
        scanned.append(rel)
        for lineno, line in enumerate(text.splitlines(), start=1):
            for needle in _RETIRED_SURFACES:
                if needle in line:
                    hits.append(f"{rel}:{lineno}: {needle!r}")
    assert_populated(scanned, "dadaia_workspace/public/data/AGENTS.md")
    assert hits == []


def test_public_assets_carry_no_portuguese_control_vocabulary() -> None:
    """Intent: CONTRACT — 0.4.7 FR4/AC4.1 (T-047-58).

    The published surface is 100 % English: a consumer meeting `Aprovado`,
    `Em revisão`, `Catálogo` or an `APROVADA/BLOQUEADA` verdict on day 1 is the
    adoption blocker this release closed. The check that enforces it at runtime is
    `public-privacy`; this contract test asserts the tree it guards is actually clean,
    so a regression fails in the suite and not only in the operator's doctor run.
    """
    offenders: list[str] = []
    files = sorted(
        path.relative_to(_REPO_ROOT).as_posix()
        for path in _PUBLIC_ROOT.rglob("*")
        if path.is_file() and path.suffix.lower() in {".md", ".json", ".py", ".txt", ".j2"}
    )
    assert_populated(files, "dadaia_workspace/public/data/AGENTS.md")
    for rel in files:
        path = _REPO_ROOT / rel
        text = path.read_text(encoding="utf-8", errors="ignore").lower()
        for term, _reason in PORTUGUESE_CONTROL_TERMS:
            if term.lower() in text:
                offenders.append(f"{rel}: {term}")
    assert offenders == [], (
        "Portuguese control vocabulary under dadaia_workspace/public/ — "
        f"translate it (0.4.7 FR4): {offenders}"
    )


# A bare `dadaia`/`dadaia-workspace` command word: not preceded by a path separator, a dot
# or a word character (so `.venv/bin/dadaia` and `dadaia_workspace` pass). The one bare
# spelling allowed is the `uvx dadaia-workspace init` bootstrap that creates the venv.
_BARE_CLI_RE = re.compile(r"(?<![\w./-])dadaia(?:-workspace)?(?= [a-z-])")
_UVX_INIT_RE = re.compile(r"uvx dadaia-workspace(?:@\S+)? init\b")
_VENV_CALL_RE = re.compile(r"\.dadaia/\.venv/bin/dadaia((?: [a-z][\w-]*)+)([^`]*)")
_FLAG_RE = re.compile(r"(?<![\w-])--[a-z][\w-]*")
# The provenance banner is a fixed literal `infrastructure/workspace_guardrail.py` matches
# byte-for-byte to recognise a projected AGENTS.md; rewording it orphans every projection.
_BANNER_SPAN = ("dadaia_workspace/public/data/AGENTS.md", 2)


def _code_spans(text: str) -> list[tuple[int, str]]:
    """Lines inside fences and inline backtick spans — what a reader copies."""
    spans: list[tuple[int, str]] = []
    fenced = False
    for number, line in enumerate(text.splitlines(), start=1):
        if line.strip().startswith("```"):
            fenced = not fenced
        elif fenced:
            spans.append((number, line))
        else:
            spans.extend((number, span) for span in re.findall(r"`([^`]+)`", line))
    return spans


def _bare_invocations(span: str) -> list[str]:
    return _BARE_CLI_RE.findall(_UVX_INIT_RE.sub("", span))


def _shipped_text() -> list[Path]:
    return sorted(
        {
            *_PUBLIC_ROOT.rglob("*.md"),
            *_PUBLIC_ROOT.rglob("*.txt"),
            *(_REPO_ROOT / "docs").glob("*.md"),
            *(_REPO_ROOT / name for name in ("README.md", "llms.txt", "CONTEXT.md")),
        }
    )


def test_all_shipped_text_invokes_the_cli_by_its_venv_path() -> None:
    """Intent: CONTRACT — shipped-text-cites-bare-dadaia-the-gate-blocks,
    shipped-text-bare-cli-guard-deleted-with-its-test. The venv-guard gate blocks a bare
    `dadaia`, so no copyable span in shipped text may spell one. Zero tolerance."""
    paths = _shipped_text()
    assert_populated([p.name for p in paths], "CONTEXT.md")
    violations = [
        f"{name}:{n}: `{span.strip()}`"
        for path in paths
        for name in [path.relative_to(_REPO_ROOT).as_posix()]
        for n, span in _code_spans(path.read_text("utf-8"))
        if _bare_invocations(span) and (name, n) != _BANNER_SPAN
    ]
    assert violations == [], "\n".join(violations)


def test_the_bare_cli_detector_spares_the_venv_path_and_uvx_init() -> None:
    assert _bare_invocations("dadaia doctor --fix") == ["dadaia"]
    assert _bare_invocations("run dadaia-workspace init x") == ["dadaia-workspace"]
    assert _bare_invocations("/w/.dadaia/.venv/bin/dadaia context list") == []
    assert _bare_invocations("uvx dadaia-workspace@0.4.8 init demo") == []


def _cli_tree() -> dict[str, set[str]]:
    """Every command path (`context bind`) mapped to the long flags it accepts."""
    from typer.main import get_command

    from dadaia_workspace.cli.main import app

    tree: dict[str, set[str]] = {}

    def walk(cmd: object, path: str) -> None:
        opts = {o for p in getattr(cmd, "params", []) for o in getattr(p, "opts", [])}
        tree[path] = {o for o in opts if o.startswith("--")} | {"--help"}
        for name, sub in (getattr(cmd, "commands", {}) or {}).items():
            walk(sub, f"{path} {name}".strip())

    walk(get_command(app), "")
    return tree


def _dead_flags(span: str, tree: dict[str, set[str]]) -> list[str]:
    match = _VENV_CALL_RE.search(span)
    if match is None:
        return []
    path = ""
    for word in match.group(1).split():
        if f"{path} {word}".strip() not in tree:
            break
        path = f"{path} {word}".strip()
    return [f for f in _FLAG_RE.findall(match.group(0)) if f not in tree[path]]


def test_every_flag_cited_beside_a_venv_call_exists_in_that_verbs_help() -> None:
    """Intent: CONTRACT — dd-cli-library-cites-a-dead-flag-and-omits-level-3,
    shipped-text-bare-cli-guard-deleted-with-its-test. A flag cited next to
    `.dadaia/.venv/bin/dadaia <verb>` in shipped text is one that verb takes."""
    tree = _cli_tree()
    violations = [
        f"{path.relative_to(_REPO_ROOT).as_posix()}:{n}: {dead}"
        for path in _shipped_text()
        for n, span in _code_spans(path.read_text("utf-8"))
        for dead in _dead_flags(span, tree)
    ]
    assert violations == [], "\n".join(violations)
    skill = (_PUBLIC_ROOT / "skills/dd-cli-library/SKILL.md").read_text("utf-8")
    assert "Level 3: `.dadaia/.venv/bin/dadaia specs init --context <ctx>`" in skill
