"""Runtime configuration generators for Claude, Codex, and OpenCode projections.

Extracted from ``FileSystemPublicAssetManager`` in ``public_assets.py`` to keep
that module under 600 lines.  Each function takes explicit arguments instead of
``self``, so there are no circular imports.
"""

from __future__ import annotations

import json
from pathlib import Path

from dadaia_workspace.infrastructure.runtime_transforms.codex_assets import (
    _render_agents_config_file_blocks,
)


def claude_settings(workspace_root: Path) -> dict[str, object]:
    """Return the Claude Code settings.json dict for *workspace_root*."""
    return {
        "hooks": {
            "PreToolUse": [
                {
                    "hooks": [
                        {
                            "command": str(
                                workspace_root / ".dadaia" / "scripts" / "sdd-spec-gate.sh"
                            ),
                            "type": "command",
                        }
                    ],
                    "matcher": "",
                },
                {
                    "hooks": [
                        {
                            "command": str(
                                workspace_root / ".dadaia" / "scripts" / "root-whitelist-gate.sh"
                            ),
                            "type": "command",
                        }
                    ],
                    "matcher": "",
                },
            ],
            "PostToolUse": [
                {
                    "hooks": [
                        {
                            "command": str(
                                workspace_root / ".dadaia" / "scripts" / "sdd-post-gate.sh"
                            ),
                            "type": "command",
                        }
                    ],
                    "matcher": "",
                }
            ],
            "UserPromptSubmit": [
                {
                    "hooks": [
                        {
                            "command": str(
                                workspace_root / ".dadaia" / "scripts" / "ctx-inject.sh"
                            ),
                            "type": "command",
                        }
                    ],
                    "matcher": "",
                }
            ],
        }
    }


def codex_config(agentic_dir: Path) -> str:
    """Return the .codex/config.toml content for *agentic_dir*."""
    lines = ['# Generated by "dadaia public install --target codex".\n', "\n"]
    lines.append("approved_commands = [\n")
    for cmd in (
        "docker",
        "make",
        "git",
        "ls",
        "find",
        "cat",
        "grep",
        "curl",
        "systemctl",
        "journalctl",
    ):
        lines.append(f'  "{cmd}",\n')
    lines.append("]\n")
    # FR7: emit [agents.<name>] config_file blocks — one per canonical agent.
    agents_blocks = _render_agents_config_file_blocks(agentic_dir / "agents")
    if agents_blocks:
        lines.append("\n")
        lines.append(agents_blocks)
    # T-PB-4: emit [skills] table after all [agents.*] blocks
    lines.append("\n")
    lines.append("[skills]\n")
    lines.append('paths = [".agents/skills", ".codex/skills"]\n')
    return "".join(lines)


def codex_hooks(workspace_root: Path) -> dict[str, object]:
    """Return the .codex/hooks.json dict for *workspace_root*."""
    write_matcher = "^(apply_patch|Edit|Write)$"
    return {
        "hooks": {
            "PreToolUse": [
                {
                    "matcher": write_matcher,
                    "hooks": [
                        {
                            "type": "command",
                            "command": str(
                                workspace_root / ".dadaia" / "scripts" / "sdd-spec-gate.sh"
                            ),
                            "statusMessage": "Checking SDD gate",
                        }
                    ],
                },
                {
                    "matcher": write_matcher,
                    "hooks": [
                        {
                            "type": "command",
                            "command": str(
                                workspace_root / ".dadaia" / "scripts" / "root-whitelist-gate.sh"
                            ),
                            "statusMessage": "Checking root whitelist",
                        }
                    ],
                },
            ],
            "PostToolUse": [
                {
                    "matcher": write_matcher,
                    "hooks": [
                        {
                            "type": "command",
                            "command": str(
                                workspace_root / ".dadaia" / "scripts" / "sdd-post-gate.sh"
                            ),
                            "statusMessage": "Refreshing SDD session heartbeat",
                        }
                    ],
                }
            ],
            # SessionStart carries the full workspace context ONCE per logical
            # session (matcher startup|resume). ctx-inject keys idempotence on the
            # session_id Codex passes on stdin, so the per-prompt UserPromptSubmit
            # path below stays silent after the first injection (T-016-C01).
            "SessionStart": [
                {
                    "matcher": "startup|resume",
                    "hooks": [
                        {
                            "type": "command",
                            "command": "DADAIA_HOOK_OUTPUT=codex-json "
                            + "DADAIA_HOOK_EVENT=SessionStart "
                            + str(workspace_root / ".dadaia" / "scripts" / "ctx-inject.sh"),
                            "statusMessage": "Loading dadaia context",
                        }
                    ],
                }
            ],
            "UserPromptSubmit": [
                {
                    "hooks": [
                        {
                            "type": "command",
                            "command": "DADAIA_HOOK_OUTPUT=codex-json "
                            + str(workspace_root / ".dadaia" / "scripts" / "ctx-inject.sh"),
                            "statusMessage": "Loading dadaia context",
                        }
                    ],
                }
            ],
        }
    }


def opencode_config(workspace_root: Path) -> dict[str, object]:
    """Return the opencode.json dict for *workspace_root*."""
    instructions: list[str] = ["AGENTS.md", "CLAUDE.md"]
    registry_json = workspace_root / ".dadaia" / "states" / "spec_contexts.json"
    if registry_json.exists():
        try:
            registry = json.loads(registry_json.read_text(encoding="utf-8"))
            for ctx in registry.get("contexts", []):
                repo_slug = ctx.get("repo_slug", "")
                if repo_slug and (workspace_root / "repos" / repo_slug / "AGENTS.md").exists():
                    instructions.append(f"repos/{repo_slug}/AGENTS.md")
        except (json.JSONDecodeError, AttributeError, KeyError):
            pass
    return {
        "$schema": "https://opencode.ai/config.json",
        "instructions": instructions,
        "permission": "allow",
    }
