"""Runtime configuration generators for Claude, Codex, and OpenCode projections.

Extracted from ``FileSystemPublicAssetManager`` in ``public_assets.py`` to keep
that module under 600 lines.  Each function takes explicit arguments instead of
``self``, so there are no circular imports.

T-018-17: hook commands are emitted as ``<python> -m dadaia_workspace.hooks.<name>``
using the venv-aware ``_python_bin()`` helper (Windows-safe fallbacks: Scripts/python.exe
→ sys.executable → bare python). The ``.sh`` scripts are superseded, not appended.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from dadaia_workspace.infrastructure.runtime_transforms.codex_assets import (
    _render_agents_config_file_blocks,
)


def _python_bin(workspace_root: Path) -> str:
    """Resolve the workspace venv Python binary, Windows-safe.

    Priority: ``.dadaia/.venv/bin/python`` (POSIX) or
    ``.dadaia/.venv/Scripts/python.exe`` (Windows) → ``sys.executable`` → bare ``python``.
    """
    from dadaia_workspace.core.platform import PLATFORM

    venv_python = (
        workspace_root
        / ".dadaia"
        / ".venv"
        / PLATFORM.venv_scripts_dir
        / f"python{PLATFORM.venv_exe_suffix}"
    )
    if venv_python.is_file():
        return str(venv_python)
    if sys.executable:
        return sys.executable
    return "python"


def _hook_cmd(workspace_root: Path, module: str) -> str:
    """Return ``<python_bin> -m <module>`` for *workspace_root*."""
    return f"{_python_bin(workspace_root)} -m {module}"


# T-010-18 (R6c, AC-R6-05, ai C-12): Claude Code PreToolUse write-gate matcher.
# The SDD gate and root-whitelist gate only police filesystem writes, so they fire
# exactly on the write tools — never on read-only / Bash tools. This scopes them
# instead of using the forbidden empty (match-all) matcher the ai audit flagged.
_CLAUDE_WRITE_TOOLS = "Edit|Write|MultiEdit|NotebookEdit"
# Claude Code's canonical explicit match-all for tool-matching events. Used on
# PostToolUse so the lease heartbeat (T-010-04) fires after *every* tool, including
# Bash, not just write tools. Deliberately the explicit "*" form, NOT the empty
# string the ai audit forbids.
_CLAUDE_MATCH_ALL = "*"


def claude_settings(workspace_root: Path) -> dict[str, object]:
    """Return the Claude Code settings.json dict for *workspace_root*."""
    return {
        "hooks": {
            "PreToolUse": [
                {
                    "hooks": [
                        {
                            "command": _hook_cmd(workspace_root, "dadaia_workspace.hooks.sdd_gate"),
                            "type": "command",
                        }
                    ],
                    "matcher": _CLAUDE_WRITE_TOOLS,
                },
                {
                    "hooks": [
                        {
                            "command": _hook_cmd(
                                workspace_root, "dadaia_workspace.hooks.root_whitelist"
                            ),
                            "type": "command",
                        }
                    ],
                    "matcher": _CLAUDE_WRITE_TOOLS,
                },
            ],
            "PostToolUse": [
                {
                    "hooks": [
                        {
                            "command": _hook_cmd(
                                workspace_root, "dadaia_workspace.hooks.sdd_post_gate"
                            ),
                            "type": "command",
                        }
                    ],
                    # Heartbeat must fire on ALL tools (T-010-04) — explicit match-all.
                    "matcher": _CLAUDE_MATCH_ALL,
                }
            ],
            # UserPromptSubmit has no tool to match; matcher unchanged (empty).
            "UserPromptSubmit": [
                {
                    "hooks": [
                        {
                            "command": _hook_cmd(
                                workspace_root, "dadaia_workspace.hooks.ctx_inject"
                            ),
                            "type": "command",
                        }
                    ],
                    "matcher": "",
                }
            ],
        }
    }


def codex_config(agentic_dir: Path) -> str:
    """Return the .codex/config.toml content for *agentic_dir*."""
    lines = ['# Generated by "dadaia public install --target codex".\n', "\n"]
    lines.append("approved_commands = [\n")
    for cmd in (
        "docker",
        "make",
        "git",
        "ls",
        "find",
        "cat",
        "grep",
        "curl",
        "systemctl",
        "journalctl",
    ):
        lines.append(f'  "{cmd}",\n')
    lines.append("]\n")
    # FR7: emit [agents.<name>] config_file blocks — one per canonical agent.
    agents_blocks = _render_agents_config_file_blocks(agentic_dir / "agents")
    if agents_blocks:
        lines.append("\n")
        lines.append(agents_blocks)
    # T-PB-4: emit [skills] table after all [agents.*] blocks
    lines.append("\n")
    lines.append("[skills]\n")
    lines.append('paths = [".agents/skills", ".codex/skills"]\n')
    return "".join(lines)


def codex_hooks(workspace_root: Path) -> dict[str, object]:
    """Return the .codex/hooks.json dict for *workspace_root*."""
    # PreToolUse write gates are scoped to the write tools only — they police
    # filesystem writes and must never fire on Bash / read-only tools.
    write_matcher = "^(apply_patch|Edit|Write)$"
    python_bin = _python_bin(workspace_root)
    ctx_inject_module = "dadaia_workspace.hooks.ctx_inject"
    return {
        "hooks": {
            "PreToolUse": [
                {
                    "matcher": write_matcher,
                    "hooks": [
                        {
                            "type": "command",
                            "command": _hook_cmd(workspace_root, "dadaia_workspace.hooks.sdd_gate"),
                            "statusMessage": "Checking SDD gate",
                        }
                    ],
                },
                {
                    "matcher": write_matcher,
                    "hooks": [
                        {
                            "type": "command",
                            "command": _hook_cmd(
                                workspace_root, "dadaia_workspace.hooks.root_whitelist"
                            ),
                            "statusMessage": "Checking root whitelist",
                        }
                    ],
                },
            ],
            # N-2 (v0.1.10 rc-2): the lease heartbeat MUST fire after *every* tool,
            # including Bash and read-only tools — otherwise a long non-write Codex
            # call (e.g. a multi-minute pytest run) starves the heartbeat and the
            # lease goes TTL-stale, the original lease-starvation incident's Codex
            # flavor. Codex's canonical match-all is an *omitted* matcher (same form
            # used by UserPromptSubmit), so the heartbeat block carries no matcher and
            # thus runs on all tools, mirroring Claude's explicit "*".
            "PostToolUse": [
                {
                    "hooks": [
                        {
                            "type": "command",
                            "command": _hook_cmd(
                                workspace_root, "dadaia_workspace.hooks.sdd_post_gate"
                            ),
                            "statusMessage": "Refreshing SDD session heartbeat",
                        }
                    ],
                }
            ],
            # SessionStart carries the full workspace context ONCE per logical
            # session (matcher startup|resume). ctx-inject keys idempotence on the
            # session_id Codex passes on stdin, so the per-prompt UserPromptSubmit
            # path below stays silent after the first injection (T-016-C01).
            "SessionStart": [
                {
                    "matcher": "startup|resume",
                    "hooks": [
                        {
                            "type": "command",
                            "command": (
                                "DADAIA_HOOK_OUTPUT=codex-json "
                                "DADAIA_HOOK_EVENT=SessionStart "
                                f"{python_bin} -m {ctx_inject_module}"
                            ),
                            "statusMessage": "Loading dadaia context",
                        }
                    ],
                }
            ],
            "UserPromptSubmit": [
                {
                    "hooks": [
                        {
                            "type": "command",
                            "command": (
                                f"DADAIA_HOOK_OUTPUT=codex-json {python_bin} -m {ctx_inject_module}"
                            ),
                            "statusMessage": "Loading dadaia context",
                        }
                    ],
                }
            ],
        }
    }


def opencode_config(workspace_root: Path) -> dict[str, object]:
    """Return the opencode.json dict for *workspace_root*."""
    instructions: list[str] = ["AGENTS.md", "CLAUDE.md"]
    registry_json = workspace_root / ".dadaia" / "states" / "spec_contexts.json"
    if registry_json.exists():
        try:
            registry = json.loads(registry_json.read_text(encoding="utf-8"))
            for ctx in registry.get("contexts", []):
                repo_slug = ctx.get("repo_slug", "")
                if repo_slug and (workspace_root / "repos" / repo_slug / "AGENTS.md").exists():
                    instructions.append(f"repos/{repo_slug}/AGENTS.md")
        except (json.JSONDecodeError, AttributeError, KeyError):
            pass
    return {
        "$schema": "https://opencode.ai/config.json",
        "instructions": instructions,
        "permission": "allow",
    }
