"""Workspace import feature — restores a workspace from a dadaia export archive."""

import json
import sys
import tarfile
from pathlib import Path

from dadaia_workspace.core.models.import_ import ImportManifest, ImportOptions, ImportResult
from dadaia_workspace.core.protocols.process_runner import ProcessRunner


class ImportService:
    def __init__(
        self,
        workspace_root: Path,
        process_runner: ProcessRunner | None = None,
    ) -> None:
        self._workspace_root = workspace_root
        # ProcessRunner: injected for tests/DI; lazily resolved to the infra adapter in
        # production when not provided.
        self._process_runner: ProcessRunner | None = process_runner

    def _get_runner(self) -> ProcessRunner:
        if self._process_runner is None:
            from dadaia_workspace.infrastructure.subprocess_runner import SubprocessProcessRunner

            self._process_runner = SubprocessProcessRunner()
        return self._process_runner

    # ── Phase 1 ─────────────────────────────────────────────────────────────

    def validate(self, archive: Path) -> ImportManifest:
        if not archive.exists():
            raise ValueError(f"Archive not found: '{archive}'. Check the path and try again.")
        if not archive.name.endswith(".tar.gz"):
            raise ValueError(
                f"Expected a .tar.gz archive, got: '{archive.name}'. "
                "Generate archives with 'dadaia export'."
            )

        try:
            with tarfile.open(archive, "r:gz") as tar:
                try:
                    member = tar.getmember("export-manifest.json")
                except KeyError as exc:
                    raise ValueError(
                        "Invalid archive: 'export-manifest.json' not found. "
                        "Only archives generated by 'dadaia export' are supported."
                    ) from exc
                f = tar.extractfile(member)
                if f is None:
                    raise ValueError("Could not read 'export-manifest.json' from archive.")
                data: dict[str, object] = json.loads(f.read())
        except tarfile.TarError as exc:
            raise ValueError(f"Cannot open archive '{archive}': {exc}") from exc

        for field in ("version", "exported_at", "workspace_root", "contexts"):
            if field not in data:
                raise ValueError(
                    f"Invalid export manifest: missing required field '{field}'. "
                    "Re-generate the archive with 'dadaia export'."
                )

        return ImportManifest(
            version=str(data["version"]),
            exported_at=str(data["exported_at"]),
            workspace_root=str(data["workspace_root"]),
            dadaia_version=str(data.get("dadaia_version", "unknown")),
            contexts=tuple(data["contexts"]),  # type: ignore[arg-type]
            includes=tuple(data.get("includes", [])),  # type: ignore[arg-type]
            mnt_included=bool(data.get("mnt_included", False)),
            reports_included=bool(data.get("reports_included", False)),
        )

    # ── Phase 2 ─────────────────────────────────────────────────────────────

    def extract(self, archive: Path, dest: Path, skip_mnt: bool) -> None:
        dest.mkdir(parents=True, exist_ok=True)
        with tarfile.open(archive, "r:gz") as tar:
            members = []
            for member in tar.getmembers():
                if skip_mnt and (member.name == "mnt" or member.name.startswith("mnt/")):
                    continue
                if member.name.endswith(".env"):
                    print(
                        f"WARNING: .env file skipped from archive: {member.name}",
                        file=sys.stderr,
                    )
                    continue
                members.append(member)
            tar.extractall(path=dest, members=members, filter="data")

    # ── Phase 3 ─────────────────────────────────────────────────────────────

    def patch_state(self, workspace_root: Path, old_root: Path) -> None:
        contexts_file = workspace_root / ".dadaia" / "states" / "spec_contexts.json"
        if not contexts_file.exists():
            return

        data: dict[str, object] = json.loads(contexts_file.read_text(encoding="utf-8"))
        # Match the old root by its POSIX form: exported configs store "/"-separated
        # paths, but str(old_root) is "\"-separated on Windows and would never match.
        # Rebuild via workspace_root / rel so output is host-native. See FR-RC2-4.
        old_posix = old_root.as_posix()

        raw_contexts = data.get("contexts", [])
        if not isinstance(raw_contexts, list):
            raw_contexts = []
        for ctx in raw_contexts:
            if not isinstance(ctx, dict):
                continue
            specs_dir = ctx.get("specs_dir")
            if isinstance(specs_dir, str) and (
                specs_dir == old_posix or specs_dir.startswith(old_posix + "/")
            ):
                rel = specs_dir[len(old_posix) :].lstrip("/")
                ctx["specs_dir"] = str(workspace_root / rel) if rel else str(workspace_root)
            ctx["state"] = "dead"
            ctx.pop("is_primary", None)
            ctx.pop("activated_at", None)
            if "alive_since" not in ctx:
                ctx["alive_since"] = None
            if "dead_since" not in ctx:
                ctx["dead_since"] = None
        data["contexts"] = raw_contexts
        # Ensure v2 schema_version is written (may be patching a v2 file)
        data["schema_version"] = "2"
        data.pop("version", None)

        tmp = contexts_file.with_suffix(".tmp")
        tmp.write_text(json.dumps(data, indent=2), encoding="utf-8")
        tmp.replace(contexts_file)

        primary_file = workspace_root / ".dadaia" / "states" / "primary_context.json"
        if primary_file.exists():
            primary_file.unlink()

        self.patch_json_paths(workspace_root, old_root)

    # ── Phase 3.5 ────────────────────────────────────────────────────────────

    # JSON config files that may contain absolute workspace paths.
    _PATH_REWRITE_TARGETS: tuple[str, ...] = (
        ".claude/settings.json",
        ".codex/hooks.json",
        ".opencode/opencode.json",
    )

    def patch_json_paths(self, workspace_root: Path, old_root: Path) -> None:
        """Rewrite absolute paths in JSON config files from old_root to workspace_root."""
        # Match by POSIX form (configs store "/"-separated paths); rebuild host-native.
        old_posix = old_root.as_posix()
        if old_posix == workspace_root.as_posix():
            return
        for rel in self._PATH_REWRITE_TARGETS:
            target = workspace_root / rel
            if not target.exists():
                continue
            try:
                data = json.loads(target.read_text(encoding="utf-8"))
                patched, count = self._rewrite_paths_in_value(data, old_posix, workspace_root)
                if count:
                    tmp = target.with_suffix(".tmp")
                    tmp.write_text(json.dumps(patched, indent=2), encoding="utf-8")
                    tmp.replace(target)
            except (json.JSONDecodeError, OSError):
                print(f"WARNING: Could not patch paths in {target}", file=sys.stderr)

    def _rewrite_paths_in_value(
        self, value: object, old: str, new: str | Path
    ) -> tuple[object, int]:
        """Recursively rewrite string values. Returns (patched_value, rewrite_count).

        ``old`` is the old workspace root in POSIX form (matches the "/"-separated
        paths stored in exported configs on any host); ``new`` is the new workspace
        root. Matched values are rebuilt as ``new / rel`` so the output uses the
        host-native separator. See FR-RC2-4.
        """
        new_root = Path(new)
        count = 0
        if isinstance(value, str):
            if value == old or value.startswith(old + "/"):
                rel = value[len(old) :].lstrip("/")
                return (str(new_root / rel) if rel else str(new_root)), 1
            return value, 0
        if isinstance(value, dict):
            result: dict[str, object] = {}
            for k, v in value.items():
                patched_v, n = self._rewrite_paths_in_value(v, old, new)
                result[k] = patched_v
                count += n
            return result, count
        if isinstance(value, list):
            items: list[object] = []
            for item in value:
                patched_item, n = self._rewrite_paths_in_value(item, old, new)
                items.append(patched_item)
                count += n
            return items, count
        return value, 0

    # ── Phase 4 ─────────────────────────────────────────────────────────────

    def bootstrap(self, workspace_root: Path) -> None:
        dadaia_bin = str(Path(sys.executable).parent / "dadaia")
        result = self._get_runner().run([dadaia_bin, "init"], cwd=workspace_root)
        if result.returncode != 0:
            raise RuntimeError(
                f"dadaia init failed (exit {result.returncode}): {result.stderr.strip()}"
            )

    # ── Phase 5 ─────────────────────────────────────────────────────────────

    def restore_contexts(
        self,
        manifest: ImportManifest,
        workspace_root: Path,
        skip: bool,
    ) -> tuple[str, ...]:
        if skip:
            return ()

        errors: list[str] = []
        # In v2, "alive" replaces "ativo"
        alive = [c for c in manifest.contexts if c.get("state") in ("alive", "ativo")]

        dadaia_bin = str(Path(sys.executable).parent / "dadaia")
        runner = self._get_runner()
        for ctx in alive:
            result = runner.run(
                [dadaia_bin, "context", "alive", str(ctx["name"])],
                cwd=workspace_root,
            )
            if result.returncode != 0:
                errors.append(f"{ctx['name']}: {result.stderr.strip()}")

        return tuple(errors)

    # ── Orchestrator ─────────────────────────────────────────────────────────

    def run(self, options: ImportOptions) -> ImportResult:
        manifest = self.validate(options.archive)

        if options.dry_run:
            self._print_dry_run(manifest, options)
            return ImportResult(
                workspace_root=options.workspace,
                contexts_restored=(),
                errors=(),
            )

        self.extract(options.archive, options.workspace, options.skip_mnt)
        self.patch_state(
            workspace_root=options.workspace,
            old_root=Path(manifest.workspace_root),
        )
        self.bootstrap(options.workspace)
        errors = self.restore_contexts(manifest, options.workspace, options.skip_activate)

        if options.skip_activate:
            restored: tuple[str, ...] = ()
        else:
            restored = tuple(
                str(c["name"]) for c in manifest.contexts if c.get("state") in ("alive", "ativo")
            )
        return ImportResult(
            workspace_root=options.workspace,
            contexts_restored=restored,
            errors=errors,
        )

    # ── Helpers ──────────────────────────────────────────────────────────────

    def _print_dry_run(self, manifest: ImportManifest, options: ImportOptions) -> None:
        print("DRY RUN — no changes will be made\n")
        print(f"Archive:        {options.archive}")
        print(f"Exported at:    {manifest.exported_at}")
        print(f"Source root:    {manifest.workspace_root}")
        print(f"Destination:    {options.workspace}")
        print(f"dadaia version: {manifest.dadaia_version}")
        alive = [c for c in manifest.contexts if c.get("state") in ("alive", "ativo")]
        print(f"\nContexts to activate ({len(alive)}):")
        for ctx in alive:
            print(f"  - {ctx['name']}  ({ctx.get('repo_url', '')})")
        if options.skip_mnt:
            print("\nmnt/ will be skipped (--skip-mnt)")
        if options.skip_activate:
            print("Context activation will be skipped (--skip-activate)")
