"""Workspace import feature — restores a workspace from a dadaia export archive."""

import json
import subprocess
import sys
import tarfile
from pathlib import Path

from dadaia_workspace.core.models.import_ import ImportManifest, ImportOptions, ImportResult


class ImportService:
    def __init__(self, workspace_root: Path) -> None:
        self._workspace_root = workspace_root

    # ── Phase 1 ─────────────────────────────────────────────────────────────

    def validate(self, archive: Path) -> ImportManifest:
        if not archive.exists():
            raise ValueError(
                f"Archive not found: '{archive}'. "
                "Check the path and try again."
            )
        if not archive.name.endswith(".tar.gz"):
            raise ValueError(
                f"Expected a .tar.gz archive, got: '{archive.name}'. "
                "Generate archives with 'dadaia export'."
            )

        try:
            with tarfile.open(archive, "r:gz") as tar:
                try:
                    member = tar.getmember("export-manifest.json")
                except KeyError:
                    raise ValueError(
                        "Invalid archive: 'export-manifest.json' not found. "
                        "Only archives generated by 'dadaia export' are supported."
                    )
                f = tar.extractfile(member)
                if f is None:
                    raise ValueError("Could not read 'export-manifest.json' from archive.")
                data: dict[str, object] = json.loads(f.read())
        except tarfile.TarError as exc:
            raise ValueError(f"Cannot open archive '{archive}': {exc}") from exc

        for field in ("version", "exported_at", "workspace_root", "contexts"):
            if field not in data:
                raise ValueError(
                    f"Invalid export manifest: missing required field '{field}'. "
                    "Re-generate the archive with 'dadaia export'."
                )

        return ImportManifest(
            version=str(data["version"]),
            exported_at=str(data["exported_at"]),
            workspace_root=str(data["workspace_root"]),
            dadaia_version=str(data.get("dadaia_version", "unknown")),
            contexts=tuple(data["contexts"]),  # type: ignore[arg-type]
            includes=tuple(data.get("includes", [])),  # type: ignore[arg-type]
            mnt_included=bool(data.get("mnt_included", False)),
            reports_included=bool(data.get("reports_included", False)),
        )

    # ── Phase 2 ─────────────────────────────────────────────────────────────

    def extract(self, archive: Path, dest: Path, skip_mnt: bool) -> None:
        dest.mkdir(parents=True, exist_ok=True)
        with tarfile.open(archive, "r:gz") as tar:
            members = []
            for member in tar.getmembers():
                if skip_mnt and (
                    member.name == "mnt" or member.name.startswith("mnt/")
                ):
                    continue
                if member.name.endswith(".env"):
                    print(
                        f"WARNING: .env file skipped from archive: {member.name}",
                        file=sys.stderr,
                    )
                    continue
                members.append(member)
            tar.extractall(path=dest, members=members, filter="data")

    # ── Phase 3 ─────────────────────────────────────────────────────────────

    def patch_state(self, workspace_root: Path, old_root: Path) -> None:
        contexts_file = workspace_root / ".dadaia" / "states" / "spec_contexts.json"
        if not contexts_file.exists():
            return

        data: dict[str, object] = json.loads(contexts_file.read_text())
        old_prefix = str(old_root)
        new_prefix = str(workspace_root)

        for ctx in data.get("contexts", []):  # type: ignore[union-attr]
            specs_dir = ctx.get("specs_dir")
            if isinstance(specs_dir, str) and specs_dir.startswith(old_prefix):
                ctx["specs_dir"] = specs_dir.replace(old_prefix, new_prefix, 1)
            ctx["state"] = "inativo"
            ctx["is_primary"] = False
            ctx["activated_at"] = None

        tmp = contexts_file.with_suffix(".tmp")
        tmp.write_text(json.dumps(data, indent=2))
        tmp.replace(contexts_file)

        primary_file = workspace_root / ".dadaia" / "states" / "primary_context.json"
        if primary_file.exists():
            primary_file.unlink()

    # ── Phase 4 ─────────────────────────────────────────────────────────────

    def bootstrap(self, workspace_root: Path) -> None:
        subprocess.run(["dadaia", "init"], cwd=workspace_root, check=True)

    # ── Phase 5 ─────────────────────────────────────────────────────────────

    def restore_contexts(
        self,
        manifest: ImportManifest,
        workspace_root: Path,
        skip: bool,
    ) -> tuple[str, ...]:
        if skip:
            return ()

        errors: list[str] = []
        ativo = [c for c in manifest.contexts if c.get("state") == "ativo"]
        primary_name = next(
            (str(c["name"]) for c in ativo if c.get("is_primary")), None
        )

        for ctx in ativo:
            result = subprocess.run(
                ["dadaia", "context", "activate", str(ctx["name"])],
                cwd=workspace_root,
                capture_output=True,
                text=True,
            )
            if result.returncode != 0:
                errors.append(f"{ctx['name']}: {result.stderr.strip()}")

        if primary_name:
            result = subprocess.run(
                ["dadaia", "context", "promote", primary_name],
                cwd=workspace_root,
                capture_output=True,
                text=True,
            )
            if result.returncode != 0:
                errors.append(f"promote {primary_name}: {result.stderr.strip()}")

        return tuple(errors)

    # ── Orchestrator ─────────────────────────────────────────────────────────

    def run(self, options: ImportOptions) -> ImportResult:
        manifest = self.validate(options.archive)

        if options.dry_run:
            self._print_dry_run(manifest, options)
            return ImportResult(
                workspace_root=options.workspace,
                contexts_restored=(),
                errors=(),
            )

        self.extract(options.archive, options.workspace, options.skip_mnt)
        self.patch_state(
            workspace_root=options.workspace,
            old_root=Path(manifest.workspace_root),
        )
        self.bootstrap(options.workspace)
        errors = self.restore_contexts(manifest, options.workspace, options.skip_activate)

        if options.skip_activate:
            restored: tuple[str, ...] = ()
        else:
            restored = tuple(
                str(c["name"]) for c in manifest.contexts if c.get("state") == "ativo"
            )
        return ImportResult(
            workspace_root=options.workspace,
            contexts_restored=restored,
            errors=errors,
        )

    # ── Helpers ──────────────────────────────────────────────────────────────

    def _print_dry_run(self, manifest: ImportManifest, options: ImportOptions) -> None:
        print("DRY RUN — no changes will be made\n")
        print(f"Archive:        {options.archive}")
        print(f"Exported at:    {manifest.exported_at}")
        print(f"Source root:    {manifest.workspace_root}")
        print(f"Destination:    {options.workspace}")
        print(f"dadaia version: {manifest.dadaia_version}")
        ativo = [c for c in manifest.contexts if c.get("state") == "ativo"]
        print(f"\nContexts to activate ({len(ativo)}):")
        for ctx in ativo:
            primary = " [primary]" if ctx.get("is_primary") else ""
            print(f"  - {ctx['name']}{primary}  ({ctx.get('repo_url', '')})")
        if options.skip_mnt:
            print("\nmnt/ will be skipped (--skip-mnt)")
        if options.skip_activate:
            print("Context activation will be skipped (--skip-activate)")
